version: '3.7'
services:
  elasticsearch:
    #    build:
    #      context: elasticsearch/
    #      args:
    #        ELASTIC_VERSION: ${ELASTIC_VERSION}
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    #      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
volumes:
  setup:
  elasticsearch:
